volumes:
  dbbackups:
  postgis-data:
  raster-db:

services:
  web-server:
    build: ./containers/web-server
    ports:
      - 80:80
    restart: on-failure

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=jamaica
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  backend:
    build: ./containers/backend
    environment:
      - PGHOST=db
      - PGDATABASE=jamaica
      - PGUSER=docker
      - PGPASSWORD=docker
    ports:
      - 8888:8080
    restart: on-failure

  raster-tileserver:
    build: ./containers/raster
    volumes:
      - raster-db:/opt/terracotta/db
      - ./mounts/raster:/opt/terracotta/data  # bind mount
    ports:
      - 5000:5000
    restart: on-failure

  vector-tileserver:
    build: ./containers/vector
    volumes:
      - ./mounts/vector:/data  # bind mount
    ports:
      - 8080:8080
    restart: on-failure
