# docker-compose build
version: '2.1'
volumes:
  dbbackups:
  postgis-data:

services:
  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=jamaica
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  api:
    build: ./backend
    ports:
      - 8888:80
    environment:
      - PGHOST=db
      - PGDATABASE=jamaica
      - PGUSER=docker
      - PGPASSWORD=docker
