version: "3.9"

services:
  web-server:
    build:
      context: ./containers/web-server
      dockerfile: Dockerfile-dev
    image: gri-web-server-dev:latest
    ports:
      - "443:443"

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - ./envs/dev/.db.env
    expose:
      - 5432
    healthcheck:
      test: "exit 0"

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./envs/dev/.pgadmin.env
    ports:
      - 5000:80

  backend:
    build: ./containers/backend
    image: gri-backend-dev:latest
    env_file:
      - ./envs/dev/.backend.env
    expose:
      - 8888

  raster-tileserver:
    build: ./containers/raster
    image: gri-raster-tilesverer-dev:latest
    volumes:
      - raster-db:/opt/terracotta/db
      - ./mounts/raster:/opt/terracotta/data # bind mount
    expose:
      - 5000

  vector-tileserver:
    build: ./containers/vector
    image: gri-vector-tilesverer-dev:latest
    volumes:
      - ./mounts/vector:/data # bind mount
    expose:
      - 8080

volumes:
  dbbackups:
  postgis-data:
  raster-db:
  pgadmin:
