version: "3.9"

services:
  web-server:
    build:
      context: ./containers/web-server
      dockerfile: Dockerfile-dev
    image: gri-web-server-dev:latest
    volumes:
      - ./containers/web-server/certs:/etc/ssl/certs
    ports:
      - 5443:443
      - 5080:80

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - ./envs/dev/.db.env
    expose:
      - 5432
    healthcheck:
      test: "exit 0"

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./envs/dev/.pgadmin.env
    ports:
      - 5050:80

  snakemake:
    image: gri-snakemake:latest
    build: ./etl
    volumes:
      - ./etl:/opt/etl
      - ./tileserver:/opt/tileserver
    command:
      [
        "--cores",
        "3",
        "--latency-wait",
        "20",
        "--resources",
        "mem_disk_gb=60",
        "--rerun-incomplete",
        "-s",
        "/opt/etl/Snakefile"
      ]

  aqueduct-downloader:
    image: gri-snakemake:latest
    build: ./etl
    volumes:
      - ./etl:/opt/etl
    entrypoint: [ "python" ]
    command:
      [
        "/opt/etl/scripts/downloaders.py",
        "aqueduct",
        "/opt/etl/hazard_layers.csv",
        "/opt/etl/raw_data/processed_data/input/hazard-aqueduct"
      ]

  backend:
    build: ./containers/backend
    image: gri-backend-dev:latest
    env_file:
      - ./envs/dev/.backend.env
    expose:
      - 8888

  raster-tileserver:
    build: ./containers/raster
    image: gri-raster-tileserver-dev:latest
    volumes:
      - ./tileserver/raster/db:/opt/terracotta/db
      - ./tileserver/raster/data:/opt/terracotta/data # bind mount
      - ./containers/raster/config.toml:/opt/config.toml
    env_file:
      - ./envs/dev/.raster-tileserver.env
    ports:
      - 5000:5000
    command: [ "serve" ]

  raster-tileserver-generator:
    build: ./containers/raster
    image: gri-raster-tileserver-dev:latest
    volumes:
      - ./tileserver/raster/db:/opt/terracotta/db
      - ./tileserver/raster/data:/opt/terracotta/data
      - ./containers/raster/config.toml:/opt/config.toml
      - ./etl/hazard_layers.csv:/opt/hazard_layers.csv
    ports:
      - 5050:5000
    command:
      [
        "python",
        "ingest.py",
        "/opt/terracotta/data",
        "/opt/hazard_layers.csv",
        "/opt/terracotta/db"
      ]

  # raster-tileserver-optimizer:
  #   build: ./containers/raster
  #   image: gri-raster-tileserver-dev:latest
  #   volumes:
  #     - ./tileserver/raster/db:/opt/terracotta/db
  #     - ./tileserver/raster/data:/opt/terracotta/data # bind mount
  #     - ./containers/raster/config.toml:/opt/config.toml
  #   command:
  #     [
  #       "terracotta",
  #       "optimize-rasters",
  #       "/opt/terracotta/data/*.tif",
  #       "-o",
  #       "/opt/terracotta/data/optimized/"
  #     ]

  vector-tileserver:
    build: ./containers/vector
    image: gri-vector-tileserver-dev:latest
    volumes:
      - ./tileserver/vector/data:/data # bind mount
      - ./containers/vector/config.json:/config.json
    expose:
      - 8080

volumes:
  dbbackups:
  postgis-data:
  pgadmin:
