version: "3.9"

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - --entryPoints.websecure.address=:443
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./containers/traefik/dev/configuration:/configuration"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./containers/traefik/dev/certs:/certs"

  web-server:
    build:
      context: ./containers/web-server
      dockerfile: Dockerfile-dev
    image: ghcr.io/nismod/gri-web-server-dev:0.7
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-server.rule=Host(`localhost`)"
      - "traefik.http.routers.web-server.entrypoints=websecure"
      - "traefik.http.routers.web-server.tls=true"
      - "traefik.http.services.web-server.loadbalancer.server.port=80"

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - ./envs/dev/.db.env
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"

  tiles-db:
    image: mysql:5.7.39
    env_file:
      - ./envs/dev/.mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./tileserver/raster/db:/var/lib/mysql
      - ./backup:/backup

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - ./envs/dev/.pgadmin.env
    ports:
      - 5050:80

  snakemake:
    image: ghcr.io/nismod/gri-snakemake:0.1
    build: ./etl
    volumes:
      - ./etl:/opt/etl
      - ./tileserver:/opt/tileserver
    env_file:
      - ./envs/dev/.snakemake.env
    command:
      [
        "--cores",
        "1",
        "--latency-wait",
        "20",
        "--resources",
        "disk_mb=60",
        "--rerun-incomplete",
        "-s",
        "/opt/etl/pipelines/osm_roads/Snakefile"
      ]

  backend:
    build: ./containers/backend
    image: ghcr.io/nismod/gri-backend:0.8
    volumes:
      - ./tileserver/raster/data:/data
    env_file:
      - ./envs/dev/.backend.env
    ports:
      - 8888:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend.loadbalancer.server.port=8888"

  vector-tileserver:
    build:
      context: ./containers/vector
      dockerfile: Dockerfile-dev
    image: ghcr.io/nismod/gri-vector-tileserver-dev:0.7
    volumes:
      - ./tileserver/vector/data:/data # bind mount
      - ./containers/vector/config-dev.json:/config.json
    ports:
      - 8800:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vector-tileserver.rule=Host(`localhost`) && PathPrefix(`/vector`)"
      - "traefik.http.routers.vector-tileserver.entrypoints=websecure"
      - "traefik.http.routers.vector-tileserver.tls=true"
      - "traefik.http.routers.vector-tileserver.middlewares=vector-tileserver-stripprefix"
      - "traefik.http.middlewares.vector-tileserver-stripprefix.stripprefix.prefixes=/vector"
      - "traefik.http.services.vector-tileserver.loadbalancer.server.port=8080"

  #### Utility Containers
  raster-tile-ingester:
    build: ./containers/raster-tile-ingester
    image: ghcr.io/nismod/gri-raster-tile-ingester:0.1
    env_file:
      - ./envs/dev/.raster-tile-ingester.env
    volumes:
      - ./containers/raster-tile-ingester/ingest.py:/ingest.py # Mounted only for Dev
      - ./tileserver/raster/data:/data # Must match path in Backend
      - ./etl/pipelines/traveltime_to_healthcare/inputs.csv:/opt/hazard_layers.csv # If loading a CSV
    command:
      [
        "load_csv",
        "--internal_raster_base_path",
        "/data/traveltime_to_healthcare",
        "--input_csv_filepath",
        "/opt/hazard_layers.csv",
        "--tile_keys",
        "type,subtype",
        "--csv_key_column_map",
        "{\"file_basename\": \"key\", \"type\": \"exposure\", \"subtype\": \"subtype\"}",
        "--database_name",
        "traveltime_to_healthcare"
      ]

  ## WARNING - Deletes all entries from the MySQL Terracotta Db for the given DB name
  raster-tile-delete-entries:
    build: ./containers/raster-tile-ingester
    image: ghcr.io/nismod/gri-raster-tile-ingester:0.1
    env_file:
      - ./envs/dev/.raster-tile-ingester.env
    volumes:
      - ./containers/raster-tile-ingester/ingest.py:/ingest.py # Mounted only for Dev
    command:
      [
        "delete_database_entries",
        "--database_name",
        "traveltime_to_healthcare"
      ]

  ## WARNING - Drop the MySQL Terracotta Db with the given DB name
  raster-tile-drop-database:
    build: ./containers/raster-tile-ingester
    image: ghcr.io/nismod/gri-raster-tile-ingester:0.1
    env_file:
      - ./envs/dev/.raster-tile-ingester.env
    volumes:
      - ./containers/raster-tile-ingester/ingest.py:/ingest.py # Mounted only for Dev
    command: [ "drop_database", "--database_name", "exposure_nature" ]

  ## WARNING - this will wipe the existing tables. TODO: Alembic
  backend-schema-regen:
    build: ./containers/backend
    image: ghcr.io/nismod/gri-backend:0.2
    volumes:
      - ./containers/backend/backend/db/models.py:/code/backend/db/models.py
    env_file:
      - ./envs/dev/.backend.env
    entrypoint: [ "python" ]
    command: [ "/code/backend/create_schema.py" ]

volumes:
  postgis-data:
  pgadmin:
