version: "3.9"

services:

  backend:
    image: ghcr.io/nismod/gri-backend:0.9
    build: ./containers/backend

  vector-tileserver:
    build:
      context: ./containers/vector
      dockerfile: Dockerfile-prod
    image: ghcr.io/nismod/gri-vector-tileserver:0.10
