# selects which env files to source prior to operations
environment: "dev" # {dev | prod}

# clip rasters to this window (decimal degrees)
#
# def gdalwarp_bounds(bbox):
#     extents = (bbox["minx"], bbox["miny"], bbox["maxx"], bbox["maxy"])
#     return " ".join(map(lambda extent: f"{extent:.3f}", extents))
#
#                minx   miny    maxx  maxy
raster_bounds: "-180.0 -84.0395 180.0 84.7879"
